# .github/workflows/flawfinder-analysis.yml
name: Flawfinder Code Scanning

permissions:
  contents: read
  security-events: write

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  flawfinder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flawfinder
        run: sudo apt-get update && sudo apt-get install -y flawfinder

      - name: Run Flawfinder to CSV
        run: |
          flawfinder --minlevel=1 --dataonly . > flawfinder.csv

      - name: Convert CSV → SARIF
        run: |
          python3 .github/scripts/filter_flawfinder_sarif.py flawfinder.csv flawfinder.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: flawfinder.sarif
