name: Run Flawfinder

permissions:
  contents: read
  actions: write

on:
  push:
    paths:
      - 'xserver/**'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install flawfinder
        run: sudo apt-get update && sudo apt-get install -y flawfinder

      - name: Run flawfinder (plain text)
        run: flawfinder ./xserver > flawfinder.txt

      - name: Run flawfinder (HTML)
        run: flawfinder --html ./xserver > flawfinder.html || echo "Flawfinder exited with error but continuing..."

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: flawfinder-reports
          path: |
            flawfinder.txt
            flawfinder.html
