# .github/workflows/flawfinder.yml
name: Flawfinder

on:
  push:
    branches: [master]
    paths-ignore: ["docs/**","test/**","vendor/**"]
  pull_request:
    branches: [master]
    paths-ignore: ["docs/**","test/**","vendor/**"]

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flawfinder
        run: sudo apt-get update && sudo apt-get install -y flawfinder python3

      - name: Run Flawfinder → raw SARIF
        run: |
          flawfinder --sarif ./ --minlevel 1 ./src > flawfinder.txt || true
          python3 .github/scripts/filter_flawfinder_sarif.py \
            flawfinder.txt flawfinder.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: flawfinder.sarif
