name: lint

on: [pull_request]
permissions:
  contents: read
jobs:
  clang-tidy:
    name: clang-tidy
    runs-on: ubuntu-latest
    steps:
      - name: C++ code check using clang/cppcheck/flawfinder
        uses: Tlazypanda/cpp-clang-check@0.13
